defaults:
  - hydra: default
  - reader: default
  - patching: default
  - segmenter: default
  - task: default
  - probing: default
  - features: patch
  - override features/patch_encoder: virchow2

device: mps
job_dir: cervical
wsi_dir: /Volumes/Data/SPRIND/cervical cancer/Mendeley LBC
wsi_ext: null
custom_mpp_keys: null
custom_list_of_wsis: /Users/frauke-mira/Documents/cervical.csv
search_nested: true
batch_size: 64
wsi_cache: null
cache_batch_size: 32
max_workers: null
skip_errors: false
