defaults:
  - hydra: default
  - reader: default
  - patching: default
  - segmenter: hest
  - task: seg
  - features: patch

device: cuda
job_dir: outputs
wsi_dir: data/wsi
wsi_ext: [svs, ndpi, tiff]
custom_mpp_keys: null
custom_list_of_wsis: null
search_nested: false
batch_size: 64
wsi_cache: null
cache_batch_size: 32
max_workers: null
skip_errors: false